/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as CastingRequestRouteImport } from './routes/casting-request'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TalentsIndexRouteImport } from './routes/talents.index'
import { Route as TalentsSlugRouteImport } from './routes/talents.$slug'
import { Route as AuthenticatedSuperadminRouteImport } from './routes/_authenticated/superadmin'
import { Route as AuthenticatedPreviewRouteImport } from './routes/_authenticated/preview'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as ApiPublicTalentsRouteImport } from './routes/api/public/talents'
import { Route as ApiPublicCastingRequestsRouteImport } from './routes/api/public/casting-requests'
import { Route as ApiPublicApplicationsRouteImport } from './routes/api/public/applications'
import { Route as ApiPublicTalentsSlugRouteImport } from './routes/api/public/talents.$slug'
import { Route as ApiPublicAuthLoginRouteImport } from './routes/api/public/auth.login'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const CastingRequestRoute = CastingRequestRouteImport.update({
  id: '/casting-request',
  path: '/casting-request',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TalentsIndexRoute = TalentsIndexRouteImport.update({
  id: '/talents/',
  path: '/talents/',
  getParentRoute: () => rootRouteImport,
} as any)
const TalentsSlugRoute = TalentsSlugRouteImport.update({
  id: '/talents/$slug',
  path: '/talents/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSuperadminRoute = AuthenticatedSuperadminRouteImport.update({
  id: '/superadmin',
  path: '/superadmin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPreviewRoute = AuthenticatedPreviewRouteImport.update({
  id: '/preview',
  path: '/preview',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiPublicTalentsRoute = ApiPublicTalentsRouteImport.update({
  id: '/api/public/talents',
  path: '/api/public/talents',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCastingRequestsRoute =
  ApiPublicCastingRequestsRouteImport.update({
    id: '/api/public/casting-requests',
    path: '/api/public/casting-requests',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicApplicationsRoute = ApiPublicApplicationsRouteImport.update({
  id: '/api/public/applications',
  path: '/api/public/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTalentsSlugRoute = ApiPublicTalentsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ApiPublicTalentsRoute,
} as any)
const ApiPublicAuthLoginRoute = ApiPublicAuthLoginRouteImport.update({
  id: '/api/public/auth/login',
  path: '/api/public/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/casting-request': typeof CastingRequestRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/preview': typeof AuthenticatedPreviewRoute
  '/superadmin': typeof AuthenticatedSuperadminRoute
  '/talents/$slug': typeof TalentsSlugRoute
  '/talents/': typeof TalentsIndexRoute
  '/api/public/applications': typeof ApiPublicApplicationsRoute
  '/api/public/casting-requests': typeof ApiPublicCastingRequestsRoute
  '/api/public/talents': typeof ApiPublicTalentsRouteWithChildren
  '/api/public/auth/login': typeof ApiPublicAuthLoginRoute
  '/api/public/talents/$slug': typeof ApiPublicTalentsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/casting-request': typeof CastingRequestRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/preview': typeof AuthenticatedPreviewRoute
  '/superadmin': typeof AuthenticatedSuperadminRoute
  '/talents/$slug': typeof TalentsSlugRoute
  '/talents': typeof TalentsIndexRoute
  '/api/public/applications': typeof ApiPublicApplicationsRoute
  '/api/public/casting-requests': typeof ApiPublicCastingRequestsRoute
  '/api/public/talents': typeof ApiPublicTalentsRouteWithChildren
  '/api/public/auth/login': typeof ApiPublicAuthLoginRoute
  '/api/public/talents/$slug': typeof ApiPublicTalentsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/casting-request': typeof CastingRequestRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/preview': typeof AuthenticatedPreviewRoute
  '/_authenticated/superadmin': typeof AuthenticatedSuperadminRoute
  '/talents/$slug': typeof TalentsSlugRoute
  '/talents/': typeof TalentsIndexRoute
  '/api/public/applications': typeof ApiPublicApplicationsRoute
  '/api/public/casting-requests': typeof ApiPublicCastingRequestsRoute
  '/api/public/talents': typeof ApiPublicTalentsRouteWithChildren
  '/api/public/auth/login': typeof ApiPublicAuthLoginRoute
  '/api/public/talents/$slug': typeof ApiPublicTalentsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/casting-request'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/signup'
    | '/verify-email'
    | '/dashboard'
    | '/preview'
    | '/superadmin'
    | '/talents/$slug'
    | '/talents/'
    | '/api/public/applications'
    | '/api/public/casting-requests'
    | '/api/public/talents'
    | '/api/public/auth/login'
    | '/api/public/talents/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/casting-request'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/signup'
    | '/verify-email'
    | '/dashboard'
    | '/preview'
    | '/superadmin'
    | '/talents/$slug'
    | '/talents'
    | '/api/public/applications'
    | '/api/public/casting-requests'
    | '/api/public/talents'
    | '/api/public/auth/login'
    | '/api/public/talents/$slug'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/casting-request'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/signup'
    | '/verify-email'
    | '/_authenticated/dashboard'
    | '/_authenticated/preview'
    | '/_authenticated/superadmin'
    | '/talents/$slug'
    | '/talents/'
    | '/api/public/applications'
    | '/api/public/casting-requests'
    | '/api/public/talents'
    | '/api/public/auth/login'
    | '/api/public/talents/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  CastingRequestRoute: typeof CastingRequestRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  TalentsSlugRoute: typeof TalentsSlugRoute
  TalentsIndexRoute: typeof TalentsIndexRoute
  ApiPublicApplicationsRoute: typeof ApiPublicApplicationsRoute
  ApiPublicCastingRequestsRoute: typeof ApiPublicCastingRequestsRoute
  ApiPublicTalentsRoute: typeof ApiPublicTalentsRouteWithChildren
  ApiPublicAuthLoginRoute: typeof ApiPublicAuthLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/casting-request': {
      id: '/casting-request'
      path: '/casting-request'
      fullPath: '/casting-request'
      preLoaderRoute: typeof CastingRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/talents/': {
      id: '/talents/'
      path: '/talents'
      fullPath: '/talents/'
      preLoaderRoute: typeof TalentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/talents/$slug': {
      id: '/talents/$slug'
      path: '/talents/$slug'
      fullPath: '/talents/$slug'
      preLoaderRoute: typeof TalentsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/superadmin': {
      id: '/_authenticated/superadmin'
      path: '/superadmin'
      fullPath: '/superadmin'
      preLoaderRoute: typeof AuthenticatedSuperadminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/preview': {
      id: '/_authenticated/preview'
      path: '/preview'
      fullPath: '/preview'
      preLoaderRoute: typeof AuthenticatedPreviewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/talents': {
      id: '/api/public/talents'
      path: '/api/public/talents'
      fullPath: '/api/public/talents'
      preLoaderRoute: typeof ApiPublicTalentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/casting-requests': {
      id: '/api/public/casting-requests'
      path: '/api/public/casting-requests'
      fullPath: '/api/public/casting-requests'
      preLoaderRoute: typeof ApiPublicCastingRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/applications': {
      id: '/api/public/applications'
      path: '/api/public/applications'
      fullPath: '/api/public/applications'
      preLoaderRoute: typeof ApiPublicApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/talents/$slug': {
      id: '/api/public/talents/$slug'
      path: '/$slug'
      fullPath: '/api/public/talents/$slug'
      preLoaderRoute: typeof ApiPublicTalentsSlugRouteImport
      parentRoute: typeof ApiPublicTalentsRoute
    }
    '/api/public/auth/login': {
      id: '/api/public/auth/login'
      path: '/api/public/auth/login'
      fullPath: '/api/public/auth/login'
      preLoaderRoute: typeof ApiPublicAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedPreviewRoute: typeof AuthenticatedPreviewRoute
  AuthenticatedSuperadminRoute: typeof AuthenticatedSuperadminRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedPreviewRoute: AuthenticatedPreviewRoute,
  AuthenticatedSuperadminRoute: AuthenticatedSuperadminRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface ApiPublicTalentsRouteChildren {
  ApiPublicTalentsSlugRoute: typeof ApiPublicTalentsSlugRoute
}

const ApiPublicTalentsRouteChildren: ApiPublicTalentsRouteChildren = {
  ApiPublicTalentsSlugRoute: ApiPublicTalentsSlugRoute,
}

const ApiPublicTalentsRouteWithChildren =
  ApiPublicTalentsRoute._addFileChildren(ApiPublicTalentsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  CastingRequestRoute: CastingRequestRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  TalentsSlugRoute: TalentsSlugRoute,
  TalentsIndexRoute: TalentsIndexRoute,
  ApiPublicApplicationsRoute: ApiPublicApplicationsRoute,
  ApiPublicCastingRequestsRoute: ApiPublicCastingRequestsRoute,
  ApiPublicTalentsRoute: ApiPublicTalentsRouteWithChildren,
  ApiPublicAuthLoginRoute: ApiPublicAuthLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
