/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as CastingRequestRouteImport } from './routes/casting-request'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TalentsIndexRouteImport } from './routes/talents.index'
import { Route as TalentsSlugRouteImport } from './routes/talents.$slug'
import { Route as AuthenticatedPreviewRouteImport } from './routes/_authenticated/preview'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as ApiPublicTalentsRouteImport } from './routes/api/public/talents'
import { Route as ApiPublicSignupRouteImport } from './routes/api/public/signup'
import { Route as ApiPublicEmbedDotjsRouteImport } from './routes/api/public/embed[.]js'
import { Route as ApiPublicCastingRequestRouteImport } from './routes/api/public/casting-request'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const CastingRequestRoute = CastingRequestRouteImport.update({
  id: '/casting-request',
  path: '/casting-request',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TalentsIndexRoute = TalentsIndexRouteImport.update({
  id: '/talents/',
  path: '/talents/',
  getParentRoute: () => rootRouteImport,
} as any)
const TalentsSlugRoute = TalentsSlugRouteImport.update({
  id: '/talents/$slug',
  path: '/talents/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPreviewRoute = AuthenticatedPreviewRouteImport.update({
  id: '/preview',
  path: '/preview',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiPublicTalentsRoute = ApiPublicTalentsRouteImport.update({
  id: '/api/public/talents',
  path: '/api/public/talents',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSignupRoute = ApiPublicSignupRouteImport.update({
  id: '/api/public/signup',
  path: '/api/public/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicEmbedDotjsRoute = ApiPublicEmbedDotjsRouteImport.update({
  id: '/api/public/embed.js',
  path: '/api/public/embed.js',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCastingRequestRoute = ApiPublicCastingRequestRouteImport.update({
  id: '/api/public/casting-request',
  path: '/api/public/casting-request',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/casting-request': typeof CastingRequestRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/preview': typeof AuthenticatedPreviewRoute
  '/talents/$slug': typeof TalentsSlugRoute
  '/talents/': typeof TalentsIndexRoute
  '/api/public/casting-request': typeof ApiPublicCastingRequestRoute
  '/api/public/embed.js': typeof ApiPublicEmbedDotjsRoute
  '/api/public/signup': typeof ApiPublicSignupRoute
  '/api/public/talents': typeof ApiPublicTalentsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/casting-request': typeof CastingRequestRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/preview': typeof AuthenticatedPreviewRoute
  '/talents/$slug': typeof TalentsSlugRoute
  '/talents': typeof TalentsIndexRoute
  '/api/public/casting-request': typeof ApiPublicCastingRequestRoute
  '/api/public/embed.js': typeof ApiPublicEmbedDotjsRoute
  '/api/public/signup': typeof ApiPublicSignupRoute
  '/api/public/talents': typeof ApiPublicTalentsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/casting-request': typeof CastingRequestRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/preview': typeof AuthenticatedPreviewRoute
  '/talents/$slug': typeof TalentsSlugRoute
  '/talents/': typeof TalentsIndexRoute
  '/api/public/casting-request': typeof ApiPublicCastingRequestRoute
  '/api/public/embed.js': typeof ApiPublicEmbedDotjsRoute
  '/api/public/signup': typeof ApiPublicSignupRoute
  '/api/public/talents': typeof ApiPublicTalentsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/casting-request'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/signup'
    | '/verify-email'
    | '/admin'
    | '/dashboard'
    | '/preview'
    | '/talents/$slug'
    | '/talents/'
    | '/api/public/casting-request'
    | '/api/public/embed.js'
    | '/api/public/signup'
    | '/api/public/talents'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/casting-request'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/signup'
    | '/verify-email'
    | '/admin'
    | '/dashboard'
    | '/preview'
    | '/talents/$slug'
    | '/talents'
    | '/api/public/casting-request'
    | '/api/public/embed.js'
    | '/api/public/signup'
    | '/api/public/talents'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/casting-request'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/signup'
    | '/verify-email'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/preview'
    | '/talents/$slug'
    | '/talents/'
    | '/api/public/casting-request'
    | '/api/public/embed.js'
    | '/api/public/signup'
    | '/api/public/talents'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  CastingRequestRoute: typeof CastingRequestRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  TalentsSlugRoute: typeof TalentsSlugRoute
  TalentsIndexRoute: typeof TalentsIndexRoute
  ApiPublicCastingRequestRoute: typeof ApiPublicCastingRequestRoute
  ApiPublicEmbedDotjsRoute: typeof ApiPublicEmbedDotjsRoute
  ApiPublicSignupRoute: typeof ApiPublicSignupRoute
  ApiPublicTalentsRoute: typeof ApiPublicTalentsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/casting-request': {
      id: '/casting-request'
      path: '/casting-request'
      fullPath: '/casting-request'
      preLoaderRoute: typeof CastingRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/talents/': {
      id: '/talents/'
      path: '/talents'
      fullPath: '/talents/'
      preLoaderRoute: typeof TalentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/talents/$slug': {
      id: '/talents/$slug'
      path: '/talents/$slug'
      fullPath: '/talents/$slug'
      preLoaderRoute: typeof TalentsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/preview': {
      id: '/_authenticated/preview'
      path: '/preview'
      fullPath: '/preview'
      preLoaderRoute: typeof AuthenticatedPreviewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/talents': {
      id: '/api/public/talents'
      path: '/api/public/talents'
      fullPath: '/api/public/talents'
      preLoaderRoute: typeof ApiPublicTalentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/signup': {
      id: '/api/public/signup'
      path: '/api/public/signup'
      fullPath: '/api/public/signup'
      preLoaderRoute: typeof ApiPublicSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/embed.js': {
      id: '/api/public/embed.js'
      path: '/api/public/embed.js'
      fullPath: '/api/public/embed.js'
      preLoaderRoute: typeof ApiPublicEmbedDotjsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/casting-request': {
      id: '/api/public/casting-request'
      path: '/api/public/casting-request'
      fullPath: '/api/public/casting-request'
      preLoaderRoute: typeof ApiPublicCastingRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedPreviewRoute: typeof AuthenticatedPreviewRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedPreviewRoute: AuthenticatedPreviewRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  CastingRequestRoute: CastingRequestRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  TalentsSlugRoute: TalentsSlugRoute,
  TalentsIndexRoute: TalentsIndexRoute,
  ApiPublicCastingRequestRoute: ApiPublicCastingRequestRoute,
  ApiPublicEmbedDotjsRoute: ApiPublicEmbedDotjsRoute,
  ApiPublicSignupRoute: ApiPublicSignupRoute,
  ApiPublicTalentsRoute: ApiPublicTalentsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
