
-- Bypass the guard_talent_flags trigger so seed rows can be inserted as approved/published
SET session_replication_role = replica;

WITH seed(user_id, slug, stage_name, full_name, gender, age, playing_age, location, nationality, native_language, categories, bio, headshot_url, showreel_link, vip, featured, featured_order, basic_info, physical, skills, languages, experience, agent, availability, agreements, extra_notes) AS (
  VALUES
  (gen_random_uuid(), 'amelia-rhodes', 'Amelia Rhodes', 'Amelia Rhodes', 'female', 28, '24-32', 'London, UK', 'British', 'English',
    ARRAY['actress']::talent_category[],
    'Trained at RADA, Amelia brings warmth and precision to leading dramatic roles in film and theatre.',
    'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=800&q=80',
    'https://vimeo.com/showreel/amelia',
    true, true, 1,
    '{"height_cm":170,"weight_kg":58,"eye_color":"green","hair_color":"auburn"}'::jsonb,
    '{"bust_cm":86,"waist_cm":62,"hips_cm":90,"shoe_eu":39,"dress_size":"S"}'::jsonb,
    '{"acting":["stage combat","accents (RP, Cockney, American)"],"sports":["horse riding","tennis"],"music":["piano"]}'::jsonb,
    '{"fluent":["English","French"],"conversational":["Italian"]}'::jsonb,
    '{"credits":[{"title":"Northern Lights","role":"Lead","year":2024,"type":"feature"},{"title":"BBC Drama Hour","role":"Recurring","year":2023,"type":"tv"}]}'::jsonb,
    '{"name":"Curtis Brown","contact":"agent@curtisbrown.co.uk"}'::jsonb,
    '{"travel":true,"based_in":"London","unavailable":[]}'::jsonb,
    '{"nudity":"none","stunt_work":"basic","release_signed":true}'::jsonb,
    '{"notes":"Holds UK and EU passport."}'::jsonb),
  (gen_random_uuid(), 'liam-ndiaye', 'Liam Ndiaye', 'Liam Ndiaye', 'male', 34, '30-40', 'Paris, France', 'French-Senegalese', 'French',
    ARRAY['actor']::talent_category[],
    'Charismatic leading man with feature and series credits across Europe and West Africa.',
    'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&q=80',
    'https://vimeo.com/showreel/liam',
    true, true, 2,
    '{"height_cm":186,"weight_kg":82,"eye_color":"brown","hair_color":"black"}'::jsonb,
    '{"chest_cm":102,"waist_cm":82,"shoe_eu":44,"suit":"40R"}'::jsonb,
    '{"acting":["motion capture","improv"],"sports":["football","boxing"],"languages":["Wolof"]}'::jsonb,
    '{"fluent":["French","English","Wolof"],"conversational":["Spanish"]}'::jsonb,
    '{"credits":[{"title":"Dakar Nights","role":"Lead","year":2023,"type":"feature"},{"title":"Canal+ Series","role":"Series Regular","year":2024,"type":"tv"}]}'::jsonb,
    '{"name":"Adequat Agency","contact":"contact@adequat.fr"}'::jsonb,
    '{"travel":true,"based_in":"Paris","unavailable":[]}'::jsonb,
    '{"nudity":"tasteful","stunt_work":"intermediate","release_signed":true}'::jsonb,
    '{"notes":"Dual French/Senegalese citizenship."}'::jsonb),
  (gen_random_uuid(), 'sofia-marin', 'Sofia Marín', 'Sofia Marín García', 'female', 24, '20-28', 'Madrid, Spain', 'Spanish', 'Spanish',
    ARRAY['model','actress']::talent_category[],
    'Editorial and runway model crossing into screen roles, signed with Elite Madrid.',
    'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=800&q=80',
    null,
    false, true, 3,
    '{"height_cm":178,"weight_kg":56,"eye_color":"hazel","hair_color":"brown"}'::jsonb,
    '{"bust_cm":84,"waist_cm":60,"hips_cm":88,"shoe_eu":40,"dress_size":"XS"}'::jsonb,
    '{"modeling":["editorial","runway","commercial"],"dance":["contemporary"]}'::jsonb,
    '{"fluent":["Spanish","English"],"conversational":["Portuguese"]}'::jsonb,
    '{"credits":[{"title":"Vogue España","role":"Editorial","year":2024,"type":"print"},{"title":"Zara SS24","role":"Campaign","year":2024,"type":"commercial"}]}'::jsonb,
    '{"name":"Elite Madrid","contact":"booking@elitemadrid.com"}'::jsonb,
    '{"travel":true,"based_in":"Madrid","unavailable":[]}'::jsonb,
    '{"nudity":"implied","stunt_work":"none","release_signed":true}'::jsonb,
    '{}'::jsonb),
  (gen_random_uuid(), 'noah-kessler', 'Noah Kessler', 'Noah Kessler', 'male', 41, '38-48', 'Berlin, Germany', 'German', 'German',
    ARRAY['actor','voice_talent']::talent_category[],
    'Veteran character actor and prolific German voice-over artist for film dubbing.',
    'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=800&q=80',
    'https://vimeo.com/showreel/noah',
    false, false, null,
    '{"height_cm":182,"weight_kg":85,"eye_color":"blue","hair_color":"salt-and-pepper"}'::jsonb,
    '{"chest_cm":104,"waist_cm":88,"shoe_eu":44}'::jsonb,
    '{"voice":["narration","character","ADR"],"acting":["drama","comedy"]}'::jsonb,
    '{"fluent":["German","English"],"conversational":["Dutch"]}'::jsonb,
    '{"credits":[{"title":"Tatort","role":"Guest","year":2024,"type":"tv"},{"title":"Netflix Dub","role":"VO Lead","year":2024,"type":"voice"}]}'::jsonb,
    '{"name":"Agentur Stimmgerecht","contact":"hello@stimmgerecht.de"}'::jsonb,
    '{"travel":true,"based_in":"Berlin","unavailable":[]}'::jsonb,
    '{"nudity":"none","stunt_work":"basic","release_signed":true}'::jsonb,
    '{}'::jsonb),
  (gen_random_uuid(), 'aaliyah-johnson', 'Aaliyah Johnson', 'Aaliyah Johnson', 'female', 22, '18-26', 'New York, USA', 'American', 'English',
    ARRAY['performer','model']::talent_category[],
    'Trained dancer and aerialist with commercial campaign experience.',
    'https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?w=800&q=80',
    null,
    false, false, null,
    '{"height_cm":168,"weight_kg":54,"eye_color":"brown","hair_color":"black"}'::jsonb,
    '{"bust_cm":82,"waist_cm":60,"hips_cm":89,"shoe_eu":38}'::jsonb,
    '{"dance":["hip-hop","contemporary","ballet"],"circus":["silks","trapeze"]}'::jsonb,
    '{"fluent":["English"],"conversational":["Spanish"]}'::jsonb,
    '{"credits":[{"title":"Nike Womens","role":"Featured Dancer","year":2024,"type":"commercial"}]}'::jsonb,
    '{"name":"Bloc NYC","contact":"agents@blocnyc.com"}'::jsonb,
    '{"travel":true,"based_in":"NYC","unavailable":[]}'::jsonb,
    '{"nudity":"none","stunt_work":"advanced","release_signed":true}'::jsonb,
    '{}'::jsonb),
  (gen_random_uuid(), 'kenji-watanabe', 'Kenji Watanabe', 'Kenji Watanabe', 'male', 29, '25-34', 'Tokyo, Japan', 'Japanese', 'Japanese',
    ARRAY['actor']::talent_category[],
    'Bilingual Japanese-English actor based between Tokyo and Los Angeles.',
    'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=800&q=80',
    'https://vimeo.com/showreel/kenji',
    false, false, null,
    '{"height_cm":175,"weight_kg":70,"eye_color":"dark brown","hair_color":"black"}'::jsonb,
    '{"chest_cm":98,"waist_cm":78,"shoe_eu":42}'::jsonb,
    '{"martial_arts":["kendo","karate"],"acting":["drama"]}'::jsonb,
    '{"fluent":["Japanese","English"]}'::jsonb,
    '{"credits":[{"title":"Tokyo Vice","role":"Co-Star","year":2024,"type":"tv"}]}'::jsonb,
    '{"name":"Top Coat","contact":"info@topcoat.co.jp"}'::jsonb,
    '{"travel":true,"based_in":"Tokyo / LA","unavailable":[]}'::jsonb,
    '{"nudity":"none","stunt_work":"intermediate","release_signed":true}'::jsonb,
    '{}'::jsonb),
  (gen_random_uuid(), 'priya-shah', 'Priya Shah', 'Priya Shah', 'female', 31, '28-36', 'Mumbai, India', 'Indian', 'Hindi',
    ARRAY['actress','voice_talent']::talent_category[],
    'Mumbai-based actress with crossover credits in Bollywood, OTT, and international voice work.',
    'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=800&q=80',
    null,
    true, false, null,
    '{"height_cm":165,"weight_kg":55,"eye_color":"brown","hair_color":"black"}'::jsonb,
    '{"bust_cm":84,"waist_cm":64,"hips_cm":90,"shoe_eu":38}'::jsonb,
    '{"acting":["drama","comedy"],"voice":["audiobook","commercial"],"dance":["bharatanatyam"]}'::jsonb,
    '{"fluent":["Hindi","English","Gujarati"],"conversational":["Marathi"]}'::jsonb,
    '{"credits":[{"title":"Made in Heaven S2","role":"Recurring","year":2023,"type":"tv"}]}'::jsonb,
    '{"name":"Yash Raj Talent","contact":"talent@yashraj.com"}'::jsonb,
    '{"travel":true,"based_in":"Mumbai","unavailable":[]}'::jsonb,
    '{"nudity":"none","stunt_work":"basic","release_signed":true}'::jsonb,
    '{}'::jsonb),
  (gen_random_uuid(), 'isabela-costa', 'Isabela Costa', 'Isabela Costa', 'female', 26, '22-30', 'São Paulo, Brazil', 'Brazilian', 'Portuguese',
    ARRAY['model','performer']::talent_category[],
    'Brazilian commercial model and fitness performer for lifestyle brands.',
    'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=800&q=80',
    null,
    false, false, null,
    '{"height_cm":172,"weight_kg":58,"eye_color":"green","hair_color":"blonde"}'::jsonb,
    '{"bust_cm":86,"waist_cm":62,"hips_cm":92,"shoe_eu":39}'::jsonb,
    '{"sports":["surfing","yoga","crossfit"],"modeling":["commercial","fitness"]}'::jsonb,
    '{"fluent":["Portuguese","English"],"conversational":["Spanish"]}'::jsonb,
    '{"credits":[{"title":"Havaianas SS24","role":"Campaign","year":2024,"type":"commercial"}]}'::jsonb,
    '{"name":"Way Model","contact":"booking@waymodel.com.br"}'::jsonb,
    '{"travel":true,"based_in":"São Paulo","unavailable":[]}'::jsonb,
    '{"nudity":"implied","stunt_work":"basic","release_signed":true}'::jsonb,
    '{}'::jsonb)
)
INSERT INTO public.talent_profiles (
  user_id, slug, stage_name, full_name, gender, age, playing_age, location, nationality, native_language,
  categories, bio, headshot_url, showreel_link, vip, featured, featured_order,
  basic_info, physical, skills, languages, experience, agent, availability, agreements, extra_notes,
  status, approved, published, visible_publicly, submitted_at, approved_at, published_at, reviewed_at
)
SELECT
  user_id, slug, stage_name, full_name, gender, age, playing_age, location, nationality, native_language,
  categories, bio, headshot_url, showreel_link, vip, featured, featured_order,
  basic_info, physical, skills, languages, experience, agent, availability, agreements, extra_notes,
  'published'::application_status, true, true, true, now(), now(), now(), now()
FROM seed
ON CONFLICT DO NOTHING;

-- Seed matching profile rows
INSERT INTO public.profiles (user_id, full_name, display_name)
SELECT tp.user_id, tp.full_name, tp.stage_name
FROM public.talent_profiles tp
WHERE tp.slug IN ('amelia-rhodes','liam-ndiaye','sofia-marin','noah-kessler','aaliyah-johnson','kenji-watanabe','priya-shah','isabela-costa')
ON CONFLICT DO NOTHING;

SET session_replication_role = DEFAULT;
